import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";

const identifier = (name) => name.replace(/[^A-Za-z0-9]+(.)/g, (_, next) => next.toUpperCase());
const pascal = (name) => {
  const value = identifier(name);
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
};
const property = (name) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
const logicalType = (descriptor) => {
  const values = Array.isArray(descriptor.type) ? descriptor.type : [descriptor.type];
  const mapped = values.map((value) => {
    if (["integer", "number"].includes(value)) return "number";
    if (value === "boolean") return "boolean";
    if (value === "json") return "unknown";
    if (value === "bytes") return "string";
    if (["date", "datetime", "instant", "int64"].includes(value)) return `string & { readonly __policysql_${value}: unique symbol }`;
    return "string";
  });
  const union = [...new Set(mapped)].join(" | ");
  return descriptor.nullable ? `${union} | null` : union;
};
const authHeaders = (token, role) => ({
  authorization: `Bearer ${token}`,
  "content-type": "application/json",
  "x-policysql-role": role,
});

export const generate = async ({ endpoint, role, input, output, token, fetchImpl = fetch }) => {
  if (!endpoint || !role || !input || !output || !token) throw new TypeError("generator options are incomplete");
  const root = new URL(endpoint);
  const headers = authHeaders(token, role);
  const request = async (path, init = {}) => {
    const response = await fetchImpl(new URL(path, root), { ...init, headers: { ...headers, ...init.headers } });
    const body = await response.json();
    if (!response.ok) throw new Error(body?.error?.code ?? `HTTP ${response.status}`);
    return body;
  };
  const [catalog, capabilities] = await Promise.all([
    request("/v1/catalog"),
    request("/v1/capabilities"),
  ]);
  if (capabilities.schemaVersion !== catalog.schemaVersion || capabilities.policyVersion !== catalog.policyVersion) {
    throw new Error("POLICYSQL_STALE_OPERATION");
  }
  const files = (await readdir(input, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith(".sql"))
    .map((entry) => entry.name)
    .sort();
  const generated = [];
  for (const file of files) {
    const sql = (await readFile(join(input, file), "utf8")).trim();
    const explain = await request("/v1/transactions:explain", {
      method: "POST",
      body: JSON.stringify({
        expected: { schemaVersion: catalog.schemaVersion, policyVersion: catalog.policyVersion },
        statements: [{ sql, params: {} }],
      }),
    });
    if (explain.statements?.length !== 1) throw new Error("Explain returned an invalid descriptor");
    const statement = explain.statements[0];
    const name = pascal(basename(file, ".sql"));
    const params = statement.parameters.map((item) => `  ${property(item.name)}: ${logicalType(item)}`).join("\n");
    const rows = statement.result.columns.map((item) => `  ${property(item.name)}: ${logicalType(item)}`).join("\n");
    const queryHash = createHash("sha256").update(sql).digest("hex");
    generated.push(`export interface ${name}Params {\n${params}\n}\n\nexport interface ${name}Row {\n${rows}\n}\n\nexport const ${identifier(basename(file, ".sql"))}: GeneratedPolicyQuery<${name}Params, ${name}Row> = {\n  sql: ${JSON.stringify(sql)},\n  queryHash: ${JSON.stringify(queryHash)},\n  schemaVersion: ${JSON.stringify(catalog.schemaVersion)},\n  policyVersion: ${JSON.stringify(catalog.policyVersion)},\n  async execute(client, params) { return (await client.execute<${name}Row>(this.sql, params)).rows },\n}\n`);
  }
  const target = resolve(output);
  const temporary = `${target}.tmp-${process.pid}-${Date.now()}`;
  await rm(temporary, { recursive: true, force: true });
  await mkdir(temporary, { recursive: true });
  await writeFile(join(temporary, "index.ts"), `// Generated by policysql generate. Do not edit.\nimport type { GeneratedPolicyQuery } from '@policysql/client'\n\n${generated.join("\n")}\n`);
  await mkdir(dirname(target), { recursive: true });
  const previous = `${target}.previous-${process.pid}`;
  await rm(previous, { recursive: true, force: true });
  try {
    await rename(target, previous).catch((error) => { if (error.code !== "ENOENT") throw error; });
    await rename(temporary, target);
    await rm(previous, { recursive: true, force: true });
  } catch (error) {
    await rm(temporary, { recursive: true, force: true });
    await rename(previous, target).catch(() => undefined);
    throw error;
  }
};
